packages:
  # Main apps
  - "apps/*"
  # Shared packages
  - "packages/*"
  # Shared UI components
  - "packages/ui/*"
  # Shared config
  - "packages/config/*"
  # Exclude test directories
  - "!**/test/**"
