name: setup-node-pnpm
description: Set up Node.js and pnpm with caching and optional installation.
inputs:
  node-version:
    description: Node.js version to install.
    required: false
    default: "20"
  pnpm-version:
    description: pnpm version to install.
    required: false
    default: "10.18.1"
  install:
    description: Run pnpm install after setup.
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version: ${{ inputs['node-version'] }}
        cache: pnpm
    - name: Setup pnpm
      uses: pnpm/action-setup@7088e561eb65bb68695d245aa206f005ef30921d # v4.1.0
      with:
        version: ${{ inputs['pnpm-version'] }}
        run_install: false
    - name: Install dependencies
      if: ${{ inputs.install == 'true' }}
      shell: bash
      run: pnpm install --frozen-lockfile
