name: Security Audit

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '0 8 * * *' # Daily at 8:00 AM UTC

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  NODE_VERSION: '20.11.0'
  PNPM_VERSION: '10.18.1'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}

      - name: Run pnpm audit
        shell: bash
        run: |
          pnpm audit --json > audit-report.json || true

      - name: Evaluate audit severity
        run: node .github/scripts/evaluate-audit.mjs

      - name: Check for outdated packages
        run: pnpm outdated || true

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          deny-licenses: GPL-3.0, AGPL-3.0, LGPL-3.0
          comment-summary-in-pr: always
